"""
_patch_notebook.py
Rewrites experiment.ipynb so that every input in INPUT_TEXTS is processed
and all results are collected into a single CSV.
Run once: python scripts/_patch_notebook.py
"""
import json
from pathlib import Path

NB_PATH = Path(__file__).parent.parent / "experiment.ipynb"

# ── New cell sources ────────────────────────────────────────────────────────

CELL_PATH_BOOTSTRAP = [
    "import sys\n",
    "from pathlib import Path\n",
    "\n",
    "# Ensure THIS directory is on the path so local modules are importable.\n",
    "NOTEBOOK_DIR = Path().resolve()  # current working directory when running the notebook\n",
    "if str(NOTEBOOK_DIR) not in sys.path:\n",
    "    sys.path.insert(0, str(NOTEBOOK_DIR))\n",
    "\n",
    "print(f\"Working dir : {NOTEBOOK_DIR}\")",
]

CELL_IMPORTS = [
    "import warnings\n",
    "\n",
    "from IPython.display import display\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "from config import (\n",
    "    # Experiment knobs\n",
    "    ABLATION_MODE,\n",
    "    EXPERIMENT_RESULTS_PATH,\n",
    "    EXPERIMENT_TAG,\n",
    "    INPUT_TEXTS,  # <- now a list\n",
    "    USER_CATEGORY,\n",
    "    # XAI method  <- change XAI_METHOD in config.py to swap\n",
    "    XAI_METHOD,\n",
    "    XAI_NUM_FEATURES,\n",
    "    XAI_NUM_SAMPLES,\n",
    "    CLASS_NAMES,\n",
    "    # LLM / decoding\n",
    "    LAMBDA_MAP,\n",
    "    NUM_BEAMS,\n",
    "    USE_CONSTRAINED_DECODING,\n",
    "    # Ontology\n",
    "    TOP_LIME_FEATURES,\n",
    ")\n",
    "from constrained_decoding import ReadabilityBeamGenerator\n",
    "from model_loaders import load_classifier, load_llm, load_ontology_model\n",
    "from pipeline_helpers import (\n",
    "    SYSTEM_PROMPT,\n",
    "    build_prompt,\n",
    "    enrich_with_ontology,\n",
    "    generate_explanation,\n",
    "    lime_coverage,\n",
    "    ontology_hit_rate,\n",
    "    predict_class,\n",
    "    readability_metrics,\n",
    "    run_xai,\n",
    ")\n",
    "\n",
    "warnings.filterwarnings(\"ignore\")\n",
    "print(\"Imports complete.\")",
]

CELL_SHOW_CONFIG = [
    "print(\"=\" * 44)\n",
    "print(\"  EXPERIMENT CONFIG\")\n",
    "print(\"=\" * 44)\n",
    "print(f\"  Tag                  : {EXPERIMENT_TAG}\")\n",
    "print(f\"  XAI method           : {XAI_METHOD}\")\n",
    "print(f\"  User category        : {USER_CATEGORY}\")\n",
    "print(f\"  Ablation mode        : {ABLATION_MODE}\")\n",
    "print(f\"  Constrained decoding : {USE_CONSTRAINED_DECODING}\")\n",
    "print(f\"  Lambda value         : {LAMBDA_MAP.get(USER_CATEGORY, 'N/A')}\")\n",
    "print(f\"  Num beams            : {NUM_BEAMS}\")\n",
    "print(f\"  Output path          : {EXPERIMENT_RESULTS_PATH}\")\n",
    "n_inputs = len(INPUT_TEXTS) if INPUT_TEXTS else '(all lines in test_data.txt)'\n",
    "print(f\"  # Inputs             : {n_inputs}\")\n",
    "print(\"=\" * 44)",
]

CELL_LOAD_INPUTS = [
    "# -- Resolve input list -------------------------------------------------------\n",
    "if INPUT_TEXTS is not None:\n",
    "    input_texts = [t.strip() for t in INPUT_TEXTS if t.strip()]\n",
    "    print(f\"[Input] Using {len(input_texts)} text(s) from config.py INPUT_TEXTS.\")\n",
    "else:\n",
    "    data_path = NOTEBOOK_DIR / \"test_data.txt\"\n",
    "    with open(data_path, encoding=\"utf-8\") as f:\n",
    "        input_texts = [ln.strip() for ln in f if ln.strip()]\n",
    "    print(f\"[Input] INPUT_TEXTS is None -- loaded {len(input_texts)} lines from test_data.txt.\")\n",
    "\n",
    "for i, t in enumerate(input_texts, 1):\n",
    "    preview = t[:120] + (\"...\" if len(t) > 120 else \"\")\n",
    "    print(f\"  [{i}] ({len(t)} chars) {preview}\")",
]

CELL_LOAD_MODELS = [
    "# -- Classifier ---------------------------------------------------------------\n",
    "clf_model, clf_pipeline = load_classifier()\n",
    "\n",
    "# -- Ontology -----------------------------------------------------------------\n",
    "ontology = load_ontology_model()\n",
    "\n",
    "# -- LLM ----------------------------------------------------------------------\n",
    "llm_tokenizer, llm_model = load_llm()\n",
    "\n",
    "# -- Constrained-decoding generator -------------------------------------------\n",
    "generator = None\n",
    "if USE_CONSTRAINED_DECODING:\n",
    "    generator = ReadabilityBeamGenerator(\n",
    "        model=llm_model,\n",
    "        tokenizer=llm_tokenizer,\n",
    "        num_beams=NUM_BEAMS,\n",
    "    )\n",
    "    print(f\"[CD] Constrained decoding enabled -- lambda={LAMBDA_MAP.get(USER_CATEGORY, '?')}, beams={NUM_BEAMS}\")\n",
    "else:\n",
    "    print(\"[CD] Constrained decoding disabled (greedy/sample mode).\")\n",
    "\n",
    "print(\"\\nAll models loaded.\")",
]

CELL_BATCH_PIPELINE = [
    "# =============================================================================\n",
    "# Batch pipeline  -- Stages 1-4 repeated for every input text\n",
    "# =============================================================================\n",
    "\n",
    "all_results = []  # collects one dict per input\n",
    "\n",
    "for idx, input_text in enumerate(input_texts, start=1):\n",
    "    print(f\"\\n{'='*64}\")\n",
    "    print(f\"  Processing input {idx}/{len(input_texts)}\")\n",
    "    print(f\"  Preview: {input_text[:80]}...\")\n",
    "    print(f\"{'='*64}\")\n",
    "\n",
    "    # -- Stage 1 : XAI feature attribution --------------------------------------\n",
    "    print(f\"\\n[Stage 1] Running {XAI_METHOD} feature attribution ...\")\n",
    "    xai_features = run_xai(\n",
    "        method=XAI_METHOD,\n",
    "        text=input_text,\n",
    "        clf_model=clf_model,\n",
    "        clf_pipeline=clf_pipeline,\n",
    "        class_names=CLASS_NAMES,\n",
    "        num_features=XAI_NUM_FEATURES,\n",
    "        num_samples=XAI_NUM_SAMPLES,\n",
    "    )\n",
    "    lime_features = xai_features\n",
    "    print(f\"[Stage 1] Top {len(lime_features)} {XAI_METHOD} features:\")\n",
    "    for word, score in lime_features:\n",
    "        print(f\"  {word:25s}  score={score:+.4f}\")\n",
    "\n",
    "    # -- Stage 2 : Ontology enrichment ------------------------------------------\n",
    "    print(\"\\n[Stage 2] Classifying text ...\")\n",
    "    predicted_class, confidence = predict_class(input_text, clf_pipeline)\n",
    "    print(f\"  Predicted class : {predicted_class}\")\n",
    "    print(f\"  Confidence      : {confidence:.4f}\")\n",
    "\n",
    "    print(\"\\n[Stage 2] Mapping features to ontology ancestors ...\")\n",
    "    feature_data = enrich_with_ontology(\n",
    "        lime_features=lime_features,\n",
    "        ontology=ontology,\n",
    "        user_category=USER_CATEGORY,\n",
    "        ablation_mode=ABLATION_MODE,\n",
    "    )\n",
    "    hit_words = [f[\"feature_word\"] for f in feature_data]\n",
    "    print(f\"  Ontology hits : {hit_words} ({len(hit_words)}/{len(lime_features[:TOP_LIME_FEATURES])} features)\")\n",
    "    for f in feature_data:\n",
    "        print(f\"    {f['feature_word']:20s} -> {f['ancestors']}\")\n",
    "\n",
    "    # -- Stage 3 : LLM explanation ----------------------------------------------\n",
    "    print(\"\\n[Stage 3] Building prompt ...\")\n",
    "    if USE_CONSTRAINED_DECODING:\n",
    "        lam = LAMBDA_MAP.get(USER_CATEGORY, LAMBDA_MAP[\"EXPERT\"])\n",
    "        print(f\"[Stage 3] Generating with constrained decoding (lambda={lam}, beams={NUM_BEAMS}) ...\")\n",
    "    else:\n",
    "        print(\"[Stage 3] Generating with standard sampling ...\")\n",
    "\n",
    "    explanation = generate_explanation(\n",
    "        text=input_text,\n",
    "        predicted_class=predicted_class,\n",
    "        feature_data=feature_data,\n",
    "        user_category=USER_CATEGORY,\n",
    "        tokenizer=llm_tokenizer,\n",
    "        model=llm_model,\n",
    "        generator=generator,\n",
    "    )\n",
    "    print(\"\\n-- Generated explanation ----------------------------------------------\")\n",
    "    print(explanation)\n",
    "    print(\"----------------------------------------------------------------------\")\n",
    "\n",
    "    # -- Stage 4 : Metrics ------------------------------------------------------\n",
    "    print(\"\\n[Stage 4] Computing metrics ...\")\n",
    "    read_metrics = readability_metrics(explanation)\n",
    "    cov = lime_coverage(explanation, feature_data)\n",
    "    hit = ontology_hit_rate(feature_data)\n",
    "\n",
    "    result = {\n",
    "        \"input_index\":           idx,\n",
    "        \"experiment_tag\":        EXPERIMENT_TAG,\n",
    "        \"xai_method\":            XAI_METHOD,\n",
    "        \"user_category\":         USER_CATEGORY,\n",
    "        \"ablation_mode\":         ABLATION_MODE,\n",
    "        \"constrained_decoding\":  USE_CONSTRAINED_DECODING,\n",
    "        \"lambda\":                LAMBDA_MAP.get(USER_CATEGORY, None),\n",
    "        \"ner_merging\":           False,\n",
    "        \"predicted_class\":       predicted_class,\n",
    "        \"confidence\":            confidence,\n",
    "        \"text_snippet\":          input_text[:120] + \"...\",\n",
    "        \"explanation\":           explanation,\n",
    "        \"lime_coverage\":         cov,\n",
    "        \"ontology_hit_rate\":     hit,\n",
    "        **read_metrics,\n",
    "    }\n",
    "    all_results.append(result)\n",
    "    fre = read_metrics.get('flesch_reading_ease', 'N/A')\n",
    "    fkgl = read_metrics.get('flesch_kincaid_grade', 'N/A')\n",
    "    print(f\"  [Done] Input {idx} -- FRE={fre:.2f}  FKGL={fkgl:.2f}  coverage={cov:.2f}  hit_rate={hit:.2f}\")\n",
    "\n",
    "print(f\"\\nBatch complete -- {len(all_results)} input(s) processed.\")",
]

CELL_SHOW_RESULTS = [
    "# Summary table for all inputs\n",
    "df = pd.DataFrame(all_results)\n",
    "\n",
    "metric_cols = [\n",
    "    \"input_index\", \"xai_method\", \"user_category\", \"ablation_mode\",\n",
    "    \"constrained_decoding\", \"ner_merging\", \"predicted_class\", \"confidence\",\n",
    "    \"flesch_reading_ease\", \"flesch_kincaid_grade\", \"smog_index\",\n",
    "    \"lime_coverage\", \"ontology_hit_rate\",\n",
    "]\n",
    "pd.set_option(\"display.max_colwidth\", 40)\n",
    "display(df[[c for c in metric_cols if c in df.columns]])",
]

CELL_SAVE_RESULTS = [
    "EXPERIMENT_RESULTS_PATH.parent.mkdir(parents=True, exist_ok=True)\n",
    "df.to_csv(EXPERIMENT_RESULTS_PATH, index=False)\n",
    "print(f\"Results saved -> '{EXPERIMENT_RESULTS_PATH}' ({len(df)} row(s))\")\n",
    "\n",
    "# Print each explanation in full\n",
    "for _, row in df.iterrows():\n",
    "    print(f\"\\n-- Input {int(row['input_index'])} \" + \"-\" * 50)\n",
    "    print(f\"  Class      : {row['predicted_class']} (conf={row['confidence']:.4f})\")\n",
    "    print(f\"  User       : {row['user_category']}\")\n",
    "    print(f\"  Ablation   : {row['ablation_mode']}\")\n",
    "    print(f\"  Tag        : {row['experiment_tag']}\")\n",
    "    print(\"-\" * 60)\n",
    "    print(row['explanation'])",
]

# ── Load notebook ───────────────────────────────────────────────────────────

with open(NB_PATH, encoding="utf-8") as fh:
    nb = json.load(fh)

def _make_code_cell(cell_id: str, source: list) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "id": cell_id,
        "metadata": {},
        "outputs": [],
        "source": source,
    }

def _make_md_cell(cell_id: str, source: list) -> dict:
    return {
        "cell_type": "markdown",
        "id": cell_id,
        "metadata": {},
        "source": source,
    }

new_cells = [
    _make_md_cell("3992bc1b", ["## 0. Path bootstrap"]),
    _make_code_cell("path-bootstrap", CELL_PATH_BOOTSTRAP),
    _make_md_cell("b96686f3", ["## 1. Imports"]),
    _make_code_cell("imports", CELL_IMPORTS),
    _make_md_cell("f89e7ce2", ["## 2. Experiment configuration (read-only -- edit config.py)"]),
    _make_code_cell("show-config", CELL_SHOW_CONFIG),
    _make_md_cell("ecd658d0", ["## 3. Input texts"]),
    _make_code_cell("load-inputs", CELL_LOAD_INPUTS),
    _make_md_cell("e059d4c4", [
        "## 4. Load models (classifier, ontology, LLM)\n",
        "\n",
        "This is the slow step. All models are loaded once here and reused across all inputs.\n",
        "NER is not loaded -- LIME/IG runs directly on raw text.",
    ]),
    _make_code_cell("load-models", CELL_LOAD_MODELS),
    _make_md_cell("2768cee4", [
        "## Stages 1-4 -- Batch pipeline\n",
        "\n",
        "Each input in `INPUT_TEXTS` is processed through:\n",
        "- **Stage 1**: XAI feature attribution (LIME or IG)\n",
        "- **Stage 2**: Ontology enrichment\n",
        "- **Stage 3**: LLM explanation generation\n",
        "- **Stage 4**: Readability & faithfulness metrics",
    ]),
    _make_code_cell("batch-pipeline", CELL_BATCH_PIPELINE),
    _make_md_cell("244962ef-results", ["## 5. Results summary"]),
    _make_code_cell("show-results", CELL_SHOW_RESULTS),
    _make_md_cell("244962ef", ["## 6. Save final results"]),
    _make_code_cell("save-results", CELL_SAVE_RESULTS),
]

nb["cells"] = new_cells

with open(NB_PATH, "w", encoding="utf-8") as fh:
    json.dump(nb, fh, indent=1, ensure_ascii=False)

print(f"[OK] Patched {NB_PATH} -- {len(new_cells)} cells written.")
